# Generated by Django 4.1.1 on 2022-09-22 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_alter_sensor_modulo'),
        ('dato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datos', to='sensor.sensor'),
        ),
        migrations.AlterField(
            model_name='dato',
            name='valor',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
