# Generated by Django 4.1.1 on 2023-11-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dato', '0003_dato_fecha_creacion_dato_fecha_edicion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dato',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'dato', 'verbose_name_plural': 'datos'},
        ),
    ]
