# Generated by Django 4.1.1 on 2022-09-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='mina',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'HERMOSILLO'), (2, 'CANANEA')], null=True, verbose_name='Mina a la que es asignado el usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='zona',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Zona de la mina a la que es asignado el usuario'),
        ),
    ]
