# Generated by Django 4.1.1 on 2022-10-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_usuario_zona_usuario_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='area',
            field=models.CharField(blank=True, choices=[('HERMOSILLO', 'HERMOSILLO'), ('CANANEA', 'CANANEA')], max_length=150, null=True, verbose_name='Area de la mina a la que es asignado el usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='mina',
            field=models.CharField(blank=True, choices=[('HERMOSILLO', 'HERMOSILLO'), ('CANANEA', 'CANANEA')], max_length=150, null=True, verbose_name='Mina a la que es asignado el usuario'),
        ),
    ]
