# Generated by Django 4.1.1 on 2022-10-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_usuario_area_alter_usuario_mina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='area',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=150, null=True, verbose_name='Area de la mina a la que es asignado el usuario'),
        ),
    ]
