# Generated by Django 4.1.1 on 2023-06-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_usuario_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'ADMIN'), (2, 'SUPERVISOR'), (3, 'OPERADOR')], default=3, verbose_name='Rol del usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='area',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Area de la mina a la que es asignado el usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='mina',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Mina a la que es asignado el usuario'),
        ),
    ]
