# Generated by Django 4.1.1 on 2022-11-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=200)),
                ('nivel_acceso', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
