# Generated by Django 4.1.1 on 2023-06-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0002_modulo_fecha_creacion_modulo_fecha_edicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='area',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='mina',
            field=models.CharField(max_length=150),
        ),
    ]
